
trigger: 
- master

pr:
- '*'

pool:
  mycomputerpool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng test
#   displayName: 'Run Angular tests'

- script: |
    npm install -g @angular/cli
    npm install
    ng serve 
  displayName: 'npm install and serve'
